package youngpeople.aliali.configuration;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;
import youngpeople.aliali.entity.member.School;
import youngpeople.aliali.repository.SchoolRepository;

@Slf4j
@Component
@RequiredArgsConstructor
public class SchoolDataConfig {

    private final SchoolRepository schoolRepository;

    @EventListener(ApplicationReadyEvent.class)
    public void schoolDataInit() {
        schoolRepository.save(new School("강릉원주대학교 강릉캠퍼스", "@gwnu.ac.kr"));
        schoolRepository.save(new School("강릉원주대학교 원주캠퍼스", "@gwnu.ac.kr"));
        schoolRepository.save(new School("강원대학교 춘천캠퍼스", "@kangwon.ac.kr"));
        schoolRepository.save(new School("강원대학교 삼척캠퍼스", "@kangwon.ac.kr"));
        schoolRepository.save(new School("경북대학교", "@knu.ac.kr"));
        schoolRepository.save(new School("경상대학교", "@gnu.ac.kr"));
        schoolRepository.save(new School("공주대학교", "@smail.kongju.ac.kr"));
        schoolRepository.save(new School("군산대학교", "@kunsan.ac.kr"));
        schoolRepository.save(new School("목포대학교", "@mokpo.ac.kr"));
        schoolRepository.save(new School("목포해양대학교", "@mmu.ac.kr"));
        schoolRepository.save(new School("부경대학교", "@gwnu.ac.kr"));
        schoolRepository.save(new School("부산대학교", "@pusan.ac.kr"));
        schoolRepository.save(new School("서울대학교", "@snu.ac.kr"));
        schoolRepository.save(new School("순천대학교", "@scnu.ac.kr"));
        schoolRepository.save(new School("안동대학교", "@anu.ac.kr"));
        schoolRepository.save(new School("전남대학교 광주캠퍼스", "@jnu.ac.kr"));
        schoolRepository.save(new School("전남대학교 여수캠퍼스", "@jnu.ac.kr"));
        schoolRepository.save(new School("전북대학교", "@jbnu.ac.kr"));
        schoolRepository.save(new School("제주대학교", "@jejunu.ac.kr"));
        schoolRepository.save(new School("창원대학교", "@changwon.ac.kr"));
        schoolRepository.save(new School("충남대학교", "@cnu.ac.kr"));
        schoolRepository.save(new School("충북대학교", "@chungbuk.ac.kr"));
        schoolRepository.save(new School("한국교원대학교", "@knue.ac.kr"));
        schoolRepository.save(new School("한국체육대학교", "@knsu.ac.kr"));
        schoolRepository.save(new School("한국해양대학교", "@kmou.ac.kr"));
        schoolRepository.save(new School("한국교통대학교", "@ut.ac.kr"));
        schoolRepository.save(new School("경남과학기술대학교", "@gntech.ac.kr"));
        schoolRepository.save(new School("서울과학기술대학교", "@seoultech.ac.kr"));
        schoolRepository.save(new School("한경대학교", "@hknu.ac.kr"));
        schoolRepository.save(new School("학밭대학교", "@hanbat.ac.kr"));
        schoolRepository.save(new School("서울시립대학교", "@uos.ac.kr"));
        schoolRepository.save(new School("가톨릭대학교 부천캠퍼스", "@catholic.ac.kr"));
        schoolRepository.save(new School("가톨릭대학교 서울캠퍼스(혜화)", "@catholic.ac.kr"));
        schoolRepository.save(new School("가톨릭대학교 서울캠퍼스(반포)", "@catholic.ac.kr"));
        schoolRepository.save(new School("감리교신학대학교", "@mtu.ac.kr"));
        schoolRepository.save(new School("강남대학교", "@kangnam.ac.kr"));
        schoolRepository.save(new School("건국대학교 서울캠퍼스", "@konkuk.ac.kr"));
        schoolRepository.save(new School("건국대학교 글로컬캠퍼스", "@kku.ac.kr"));
        schoolRepository.save(new School("건양대학교 논산캠퍼스", "@konyang.ac.kr"));
        schoolRepository.save(new School("건양대학교 대전캠퍼스", "@konyang.ac.kr"));
        schoolRepository.save(new School("경기대학교 수원캠퍼스", "@kyonggi.ac.kr"));
        schoolRepository.save(new School("경기대학교 서울캠퍼스", "@kyonggi.ac.kr"));
        schoolRepository.save(new School("경남대학교", "@hanma.ac.kr"));
        schoolRepository.save(new School("경동대학교", "@k1.ac.kr"));
        schoolRepository.save(new School("대구한의대학교", "@dhu.ac.kr"));
        schoolRepository.save(new School("경성대학교", "@ks.ac.kr"));
        schoolRepository.save(new School("가천대학교", "@gachon.ac.kr"));
        schoolRepository.save(new School("경일대학교", "@kiu.kr"));
        schoolRepository.save(new School("경주대학교", "@gju.ac.kr"));
        schoolRepository.save(new School("금오공과대학교", "@kumoh.ac.kr"));
        schoolRepository.save(new School("경희대학교 수원캠퍼스", "@khu.ac.kr"));
        schoolRepository.save(new School("경희대학교 서울캠퍼스", "@khu.ac.kr"));
        schoolRepository.save(new School("계명대학교", "@kmu.ac.kr"));
        schoolRepository.save(new School("고려대학교 서울캠퍼스", "@korea.ac.kr"));
        schoolRepository.save(new School("고려대학교 세종캠퍼스", "@korea.ac.kr"));
        schoolRepository.save(new School("고려대학교 세종캠퍼스", "@korea.ac.kr"));
        schoolRepository.save(new School("고신대학교", "@kosin.ac.kr"));
        schoolRepository.save(new School("가톨릭관동대학교", "@cku.ac.kr"));
        schoolRepository.save(new School("광신대학교", "@kwangshin.ac.kr"));
        schoolRepository.save(new School("광운대학교", "@kw.ac.kr"));
        schoolRepository.save(new School("광주가톨릭대학교", "@kjcatholic.ac.kr"));
        schoolRepository.save(new School("광주여자대학교", "@kwu.ac.kr"));
        schoolRepository.save(new School("국민대학교", "@kookmin.ac.kr"));
        schoolRepository.save(new School("강서대학교", "@kcu.ac.kr"));
        schoolRepository.save(new School("극동대학교", "@kdu.ac.kr"));
        schoolRepository.save(new School("나사렛대학교", "@kornu.ac.kr"));
        schoolRepository.save(new School("단국대학교", "@dankook.ac.kr"));
        schoolRepository.save(new School("대구대학교", "@daegu.ac.kr"));
        schoolRepository.save(new School("대구예술대학교", "@dgau.ac.kr"));
        schoolRepository.save(new School("대구카톨릭대학교", "@cu.ac.kr"));
        schoolRepository.save(new School("대전대학교", "@edu.dju.ac.kr"));
        schoolRepository.save(new School("대진대학교", "@daejun.ac.kr"));
        schoolRepository.save(new School("서울기독대학교", "@scu.ac.kr"));
        schoolRepository.save(new School("덕성여자대학교", "@duksung.ac.kr"));
        schoolRepository.save(new School("동국대학교 서울캠퍼스", "@dongguk.edu"));
        schoolRepository.save(new School("동국대학교 경주캠퍼스", "@dongguk.ac.kr"));
        schoolRepository.save(new School("동덕여대학교", "@dongduk.ac.kr"));
        schoolRepository.save(new School("동서대학교", "@dongseo.ac.kr"));
        schoolRepository.save(new School("동신대학교", "@dsu.kr"));
        schoolRepository.save(new School("동아대학교", "@donga.ac.kr"));
        schoolRepository.save(new School("루터대학교", "@ltu.ac.kr"));
        schoolRepository.save(new School("명지대학교 용인캠퍼스", "@mju.ac.kr"));
        schoolRepository.save(new School("명지대학교 서울캠퍼스", "@mju.ac.kr"));
        schoolRepository.save(new School("목원대학교", "@mokwon.ac.kr"));
        schoolRepository.save(new School("배재대학교", "@pcu.ac.kr"));
        schoolRepository.save(new School("부산가톨릭대학교", "@cup.ac.kr"));
        schoolRepository.save(new School("부산외국어대학교", "@bufs.ac.kr"));
        schoolRepository.save(new School("삼육대학교", "@syuin.ac.kr"));
        schoolRepository.save(new School("상명대학교 서울캠퍼스", "@sangmyung.kr"));
        schoolRepository.save(new School("상명대학교 천안캠퍼스", "@sangmyung.kr"));
        schoolRepository.save(new School("상지대학교", "@sangji.ac.kr"));
        schoolRepository.save(new School("서강대학교", "@sogang.ac.kr"));
        schoolRepository.save(new School("서경대학교", "@skuniv.ac.kr"));
        schoolRepository.save(new School("서울신학대학교", "@stu.ac.kr"));
        schoolRepository.save(new School("서울여자대학교", "@swu.ac.kr"));
        schoolRepository.save(new School("서울장신대학교", "@sjs.ac.kr"));
        schoolRepository.save(new School("서원대학교", "@seowon.ac.kr"));
        schoolRepository.save(new School("선문대학교", "@sunmoon.ac.kr"));
        schoolRepository.save(new School("성결대학교", "@sungkyul.ac.kr"));
        schoolRepository.save(new School("성공회대학교", "@skhu.ac.kr"));
        schoolRepository.save(new School("성균관대학교 서울캠퍼스", "@skku.edu"));
        schoolRepository.save(new School("성균관대학교 수원캠퍼스", "@skku.edu"));
        schoolRepository.save(new School("성신여대학교", "@sungshin.ac.kr"));
        schoolRepository.save(new School("세명대학교", "@semyung.ac.kr"));
        schoolRepository.save(new School("세종대학교", "@sju.ac.kr"));
        schoolRepository.save(new School("수원가톨릭대학교", "@suwoncatholic.ac.kr"));
        schoolRepository.save(new School("수원대학교", "@suwon.ac.kr"));
        schoolRepository.save(new School("숙명여자대학교", "@sookmyung.ac.kr"));
        schoolRepository.save(new School("순천향대학교", "@sch.ac.kr"));
        schoolRepository.save(new School("숭실대학교", "@soongsil.ac.kr"));
        schoolRepository.save(new School("신라대학교", "@soongsil.ac.kr"));
        schoolRepository.save(new School("아신대학교", "@acts.university"));
        schoolRepository.save(new School("아주대학교", "@ajou.ac.kr"));
        schoolRepository.save(new School("안양대학교", "@ayum.anyang.ac.kr"));
        schoolRepository.save(new School("연세대학교", "@yonsei.ac.kr"));
        schoolRepository.save(new School("연세대학교 원주캠퍼스", "@yonsei.ac.kr"));
        schoolRepository.save(new School("영남대학교", "@ynu.ac.kr"));
        schoolRepository.save(new School("영남신학대학교", "@ytus.ac.kr"));
        schoolRepository.save(new School("유원대학교", "@u1.ac.kr"));
        schoolRepository.save(new School("영산선학대학교", "@youngsan.ac.kr"));
        schoolRepository.save(new School("용인대학교", "@yiu.ac.kr"));
        schoolRepository.save(new School("우석대학교", "@woosuk.ac.kr"));
        schoolRepository.save(new School("울산대학교", "@ulsan.ac.kr"));
        schoolRepository.save(new School("원광대학교", "@wonkwang.ac.kr"));
        schoolRepository.save(new School("위덕대학교", "@uu.ac.kr"));
        schoolRepository.save(new School("을지대학교 성남캠퍼스", "@eulji.ac.kr"));
        schoolRepository.save(new School("을지대학교 의정부 캠퍼스", "@uu.ac.kr"));
        schoolRepository.save(new School("이화여자대학교", "@ewhain.net"));
        schoolRepository.save(new School("인제대학교 김해캠퍼스", "@inje.ac.kr"));
        schoolRepository.save(new School("인제대학교 부산캠퍼스", "@inje.ac.kr"));
        schoolRepository.save(new School("인천가톨릭대학교 강화캠퍼스", "@iccu.ac.kr"));
        schoolRepository.save(new School("인천가톨릭대학교 송도캠퍼스", "@iccu.ac.kr"));
        schoolRepository.save(new School("인하대학교", "@inha.edu"));
        schoolRepository.save(new School("장로회신학대학교", "@pcts.ac.kr"));
        schoolRepository.save(new School("전주대학교", "@jj.ac.kr"));
        schoolRepository.save(new School("조선대학교", "@chosun.kr"));
        schoolRepository.save(new School("중부대학교", "@jmail.ac.kr"));
        schoolRepository.save(new School("중앙대학교 서울캠퍼스", "@cau.ac.kr"));
        schoolRepository.save(new School("중앙대학교 안성캠퍼스", "@cau.ac.kr"));
        schoolRepository.save(new School("중앙승가대학교", "@sangha.ac.kr"));
        schoolRepository.save(new School("백석대학교", "@bu.ac.kr"));
        schoolRepository.save(new School("청주대학교", "@cju.ac.kr"));
        schoolRepository.save(new School("총신대학교", "@cju.ac.kr"));
        schoolRepository.save(new School("추계예술대학교", "@chugye.ac.kr"));
        schoolRepository.save(new School("한국침례신학대학교", "@kbtus.ac.kr"));
        schoolRepository.save(new School("칼빈대학교", "@calvin.ac.kr"));
        schoolRepository.save(new School("평택대학교", "@ptu.ac.kr"));
        schoolRepository.save(new School("차의과학대학교", "@cha.ac.kr"));
        schoolRepository.save(new School("포항공과대학교", "@postech.ac.kr."));
        schoolRepository.save(new School("한국기술교육대학교", "@koreatech.ac.kr"));
        schoolRepository.save(new School("한국성서대학교", "@bible.ac.kr"));
        schoolRepository.save(new School("한국외국어대학교", "@hufs.ac.kr"));
        schoolRepository.save(new School("한국항공대학교", "@kau.ac.kr"));
        schoolRepository.save(new School("한남대학교", "@hannam.ac.kr"));
        schoolRepository.save(new School("한동대학교", "@handong.edu"));
        schoolRepository.save(new School("한라대학교", "@halla.ac.kr"));
        schoolRepository.save(new School("한림대학교", "@hallym.ac.kr"));
        schoolRepository.save(new School("한서대학교", "@hanseo.ac.kr"));
        schoolRepository.save(new School("한성대학교", "@hansung.ac.kr"));
        schoolRepository.save(new School("한세대학교", "@uohs.ac.kr"));
        schoolRepository.save(new School("한신대학교", "@hs.ac.kr"));
        schoolRepository.save(new School("한양대학교 서울캠퍼스", "@hanyang.ac.kr"));
        schoolRepository.save(new School("한양대학교 에리카캠퍼스", "@hanyang.ac.kr"));
        schoolRepository.save(new School("서울한영대학교", "@hytu.ac.kr"));
        schoolRepository.save(new School("한일장신대학교", "@hanil.ac.kr"));
        schoolRepository.save(new School("협성대학교", "@uhs.ac.kr"));
        schoolRepository.save(new School("호남대학교", "@honam.ac.kr"));
        schoolRepository.save(new School("호남신학대학교", "@htus.ac.kr"));
        schoolRepository.save(new School("호서대학교", "@hoseo.edu"));
        schoolRepository.save(new School("홍익대학교 서울캠퍼스", "@hongik.ac.kr"));
        schoolRepository.save(new School("홍익대학교 세종캠퍼스", "@hongik.ac.kr"));
        schoolRepository.save(new School("가톨릭꽃동네대학교", "@kkot.ac.kr"));
        schoolRepository.save(new School("남부대학교", "@nambu.ac.kr"));
        schoolRepository.save(new School("예원예술대학교 임실캠퍼스", "@yewon.ac.kr"));
        schoolRepository.save(new School("예원예술대학교 양주캠퍼스", "@yewon.ac.kr"));
        schoolRepository.save(new School("목포가톨릭대학교", "@mcu.ac.kr"));
        schoolRepository.save(new School("부산장신대학교", "@bpu.ac.kr"));
        schoolRepository.save(new School("금강대학교", "@ggu.ac.kr"));
        schoolRepository.save(new School("예수대학교", "@jesus.ac.kr"));
        schoolRepository.save(new School("한국국제대학교", "@iuk.ac.kr"));
        schoolRepository.save(new School("광주대학교", "@gwangju.ac.kr"));
        schoolRepository.save(new School("신경대학교", "@sgu.ac.kr"));
        schoolRepository.save(new School("영산대학교 양산캠퍼스", "@ysu.ac.kr"));
        schoolRepository.save(new School("영산대학교 해운대캠퍼스", "@ysu.ac.kr"));
        schoolRepository.save(new School("대전신학대학교", "@daejeon.ac.kr"));
        schoolRepository.save(new School("중원대학교", "@jwu.ac.kr"));
        schoolRepository.save(new School("우송대학교", "@wsu.ac.kr"));
        schoolRepository.save(new School("김천대학교", "@gimcheon.ac.kr"));
        schoolRepository.save(new School("송원대학교", "@songwon.ac.kr"));
        schoolRepository.save(new School("경운대학교", "@ikw.ac.kr"));
        schoolRepository.save(new School("남서울대학교", "@nsu.ac.kr"));
        schoolRepository.save(new School("초당대학교", "@nsu.ac.kr"));
        schoolRepository.save(new School("한국공학대학교", "@tukorea.ac.kr"));
        schoolRepository.save(new School("제주국제대학교", "@jeju.ac.kr"));
        schoolRepository.save(new School("창신대학교", "@csc.ac.kr"));
        schoolRepository.save(new School("울산과학기술원(UNIST)", "@unist.ac.kr"));
        schoolRepository.save(new School("공주교육대학교", "@gjue.ac.kr"));
        schoolRepository.save(new School("광주교육대학교", "@gnue.ac.kr"));
        schoolRepository.save(new School("대구교육대학교", "@dnue.ac.kr"));
        schoolRepository.save(new School("부산대학교", "@dnue.ac.kr"));

        log.info("Initiating school data is complete");
    }

}
